package com.jiuqi.dna.gams.jy03.printing.setting;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-12-12T15:35:43.243+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", name = "PrintingTerminalSetting")
//@XmlSeeAlso({ObjectFactory.class})
public interface PrintingTerminalSetting {

    @WebMethod
    @RequestWrapper(localName = "updatePrintedNum", targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", className = "com.jiuqi.dna.printing.jy03.webservcie.setting.UpdatePrintedNum")
    @ResponseWrapper(localName = "updatePrintedNumResponse", targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", className = "com.jiuqi.dna.printing.jy03.webservcie.setting.UpdatePrintedNumResponse")
    public void updatePrintedNum(
        @WebParam(name = "settingObj", targetNamespace = "")
        SettingObject settingObj
    );

    @WebMethod
    @RequestWrapper(localName = "setSettingNum", targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", className = "com.jiuqi.dna.printing.jy03.webservcie.setting.SetSettingNum")
    @ResponseWrapper(localName = "setSettingNumResponse", targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", className = "com.jiuqi.dna.printing.jy03.webservcie.setting.SetSettingNumResponse")
    public void setSettingNum(
        @WebParam(name = "settingObj", targetNamespace = "")
        SettingObject settingObj
    );

    @WebMethod
    @RequestWrapper(localName = "querySetting", targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", className = "com.jiuqi.dna.printing.jy03.webservcie.setting.QuerySetting")
    @ResponseWrapper(localName = "querySettingResponse", targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", className = "com.jiuqi.dna.printing.jy03.webservcie.setting.QuerySettingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public SettingObject querySetting(
        @WebParam(name = "settingObj", targetNamespace = "")
        SettingObject settingObj
    );

    @WebMethod
    @RequestWrapper(localName = "queryMinRemainingNumSetting", targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", className = "com.jiuqi.dna.printing.jy03.webservcie.setting.QueryMinRemainingNumSetting")
    @ResponseWrapper(localName = "queryMinRemainingNumSettingResponse", targetNamespace = "http://setting.webservcie.printing.jy03.gams.dna.jiuqi.com/", className = "com.jiuqi.dna.printing.jy03.webservcie.setting.QueryMinRemainingNumSettingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public SettingObject queryMinRemainingNumSetting(
        @WebParam(name = "settingObj", targetNamespace = "")
        SettingObject settingObj
    );
}
