package com.jiuqi.dna.gams.jy03.printing.setting;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-12-12T15:35:43.368+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "PrintingTerminalSettingWebService",
                  wsdlLocation = "http://127.0.0.1:8084/dna_ws/PrintingTerminalSetting?wsdl",
                  targetNamespace = "jy03")
public class PrintingTerminalSettingWebService extends Service {

    public final static QName SERVICE = new QName("jy03", "PrintingTerminalSettingWebService");
    public final static QName PrintingTerminalSettingPort = new QName("jy03", "PrintingTerminalSettingPort");

    public PrintingTerminalSettingWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     *
     * @return
     *     returns PrintingTerminalSetting
     */
    @WebEndpoint(name = "PrintingTerminalSettingPort")
    public PrintingTerminalSetting getPrintingTerminalSettingPort() {
        return super.getPort(PrintingTerminalSettingPort, PrintingTerminalSetting.class);
    }


    
}
