package com.jiuqi.dna.gams.jy03.printing.billcommonwebservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-24T10:20:22.371+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "PrintTerminalBillCommonService",
                  targetNamespace = "PrintTerminal")
public class PrintingTerminalBillCommonWebService extends Service {

    public final static QName SERVICE = new QName("PrintTerminal", "PrintTerminalBillCommonService");
    public final static QName PrintingTerminalBillCommonPort = new QName("PrintTerminal", "PrintTerminalBillCommonPort");
    public PrintingTerminalBillCommonWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     *
     * @return
     *     returns PrintingTerminalBillCommon
     */
    @WebEndpoint(name = "PrintTerminalBillCommonPort")
    public PrintingTerminalBillCommon getPrintingTerminalBillCommonPort() {
        return super.getPort(PrintingTerminalBillCommonPort, PrintingTerminalBillCommon.class);
    }

    
}
