package com.jiuqi.dna.gams.jy03.printing.billcommonwebservice;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-24T10:20:22.298+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", name = "PrintTerminalBillCommonService")
//@XmlSeeAlso({ObjectFactory.class})
public interface PrintingTerminalBillCommon {

    @WebMethod
    @RequestWrapper(localName = "getPDFData", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalBillCommonService.GetPDFData")
    @ResponseWrapper(localName = "getPDFDataResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalBillCommonService.GetPDFDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<byte[]> getPDFData(
        @WebParam(name = "dataList", targetNamespace = "")
        java.util.List<BillCommonFieldsEntity> dataList,
        @WebParam(name = "printType", targetNamespace = "")
        java.lang.String printType,
        @WebParam(name = "printName", targetNamespace = "")
        java.lang.String printName
    );
    
    @WebMethod
    @RequestWrapper(localName = "getPrintModel", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalBillCommonService.getPrintModel")
    @ResponseWrapper(localName = "getPrintModelResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalBillCommonService.getPrintModelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<String> getPrintModel(
        @WebParam(name = "billDefine", targetNamespace = "")
        java.lang.String billDefine,
        @WebParam(name = "printType", targetNamespace = "")
        java.lang.String printType
    );
    
    @WebMethod
    @RequestWrapper(localName = "getDataList", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalBillCommonService.GetDataList")
    @ResponseWrapper(localName = "getDataListResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalBillCommonService.GetDataListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<BillCommonFieldsEntity> getDataList(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "pageIndex", targetNamespace = "")
        java.lang.Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        java.lang.Integer pageSize,
        @WebParam(name = "value", targetNamespace = "")
        java.lang.String value,
        @WebParam(name = "workflowstate", targetNamespace = "")
        java.lang.String workflowstate,
        @WebParam(name = "billDefine", targetNamespace = "")
        java.lang.String billDefine
    );
    
    @WebMethod
    @RequestWrapper(localName = "checkHasTenW", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalBillCommonService.checkHasTenW")
    @ResponseWrapper(localName = "checkHasTenWResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalBillCommonService.checkHasTenWResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean checkHasTenW(
        @WebParam(name = "billId", targetNamespace = "")
        java.lang.String billId,
        @WebParam(name = "billDefine", targetNamespace = "")
        java.lang.String billDefine
    );
}
