package com.jiuqi.dna.gams.jy03.printing.cardwebservice;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-08-16T23:54:05.314+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", name = "PrintTerminalAssetCardService")
//@XmlSeeAlso({ObjectFactory.class})
public interface PrintingTerminalAssetCard {

    @WebMethod
    @RequestWrapper(localName = "getPDFData", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalAssetCardService.GetPDFData")
    @ResponseWrapper(localName = "getPDFDataResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalAssetCardService.getPDFDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<byte[]> getPDFData(
        @WebParam(name = "cardList", targetNamespace = "")
        java.util.List<AssetCard> cardList,
        @WebParam(name = "printType", targetNamespace = "")
        java.lang.String printType
    );

    @WebMethod
    @RequestWrapper(localName = "getCardList", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalAssetCardService.getCardList")
    @ResponseWrapper(localName = "getCardListResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalAssetCardService.getCardListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<AssetCard> getCardList(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "pageIndex", targetNamespace = "")
        java.lang.Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        java.lang.Integer pageSize,
        @WebParam(name = "value", targetNamespace = "")
        java.lang.String value
    );

    @WebMethod
    @RequestWrapper(localName = "getOwnCardList", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalAssetCardService.getOwnCardList")
    @ResponseWrapper(localName = "getOwnCardListResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalAssetCardService.getOwnCardListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<AssetCard> getOwnCardList(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "pageIndex", targetNamespace = "")
        java.lang.Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "")
        java.lang.Integer pageSize,
        @WebParam(name = "value", targetNamespace = "")
        java.lang.String value
    );
}
