package com.jiuqi.dna.gams.jy03.printing.cardwebservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-08-16T23:54:05.511+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "PrintTerminalAssetCardService",
                  targetNamespace = "PrintTerminal")
public class PrintingTerminalAssetCardWebService extends Service {

    public final static QName SERVICE = new QName("PrintTerminal", "PrintTerminalAssetCardService");
    public final static QName PrintingTerminalAssetCardPort = new QName("PrintTerminal", "PrintTerminalAssetCardPort");
    public PrintingTerminalAssetCardWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     *
     * @return
     *     returns PrintingTerminalAssetCard
     */
    @WebEndpoint(name = "PrintingTerminalAssetCardPort")
    public PrintingTerminalAssetCard getPrintingTerminalAssetCardPort() {
        return super.getPort(PrintingTerminalAssetCardPort, PrintingTerminalAssetCard.class);
    }

}
