package com.jiuqi.dna.gams.jy03.printing.loginwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2018-05-10T15:49:48.993+08:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", name = "PrintTerminalLoginService")
//@XmlSeeAlso({ObjectFactory.class})
public interface PrintingTerminalLogin {

    @WebMethod
    @RequestWrapper(localName = "checkUser", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalLoginService.checkUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalLoginService.CheckUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkUser(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
    @WebMethod  
    @RequestWrapper(localName = "checkCampusCard", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalLoginService.checkCampusCard")
    @ResponseWrapper(localName = "checkCampusCardResponse", targetNamespace = "http://service.webservice.printterminal.xgd.jy.gams2.np.jiuqi.com/", className = "com.jiuqi.np.gams2.jy.xgd.printterminal.webservice.service.PrintTerminalLoginService.checkCampusCardResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkCampusCard(
        @WebParam(name = "wlkh", targetNamespace = "")
        java.lang.String wlkh
    );
    
    
    
}
